### ISSUE TITLE
java.lang.NoClassDefFoundError: com/pi4j/io/serial/SerialFactory

### ISSUE THREAD

**Issue by vowovrz** [harf18/escpospi#1]
cmd : cd '/home/pi/NetBeansProjects//Test'; 'sudo' '/usr/lib/jvm/java-8-openjdk-armhf/bin/java'  -Dfile.encoding=UTF-8   -jar /home/pi/NetBeansProjects//Test/dist/Test.jar 
Exception in thread "main" 
java.lang.NoClassDefFoundError: com/pi4j/io/serial/SerialFactory

Caused by: java.lang.ClassNotFoundException: com.pi4j.io.serial.SerialFactory

**Comment by vowovrz** [comment]
Everything is fine,thx

**Comment by harf18** [comment]
Thank you for your feedback, you have been faster than me ! :)
