### ISSUE TITLE
issue while running the code

### ISSUE THREAD

**Issue by dilagurung** [harf18/escpospi#4]
SEVERE: Unable to load [libpi4j.so] using path: [/lib/libpi4j.so]
java.lang.IllegalArgumentException: The path has to be absolute, but found: \lib\libpi4j.so

**Comment by harf18** [comment]
Hello,

When did you have this issue ? At the execution on the raspberry pi ?

did you install wiring pi ?

**Comment by dilagurung** [comment]
i have tried it windows and linux.

**Comment by harf18** [comment]
It's working only on raspberry Pi, and you have to install "wiring pi"
